version: "3.8"

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "8108:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php
    networks:
      - laravel_network

  php:
    build:
      context: php
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - laravel_network

  mysql:
    image: alpine/mysql:latest
    ports:
      - "3396:3306"
    env_file:
      - mysql/mysql.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  composer:
    build:
      context: php
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - laravel_network

  artisan:
    build:
      context: php
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    ports:
      - "8980:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=password
      - UPLOAD_LIMIT=128M
    depends_on:
      - mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge