services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "8108:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - php
      - mysql
    networks:
      - laravel_network

  php:
    build:
      context: php
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    ports:
      - "3396:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10
      start_period: 30s

  composer:
    build:
      context: php
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    depends_on:
      - mysql
    networks:
      - laravel_network

  artisan:
    build:
      context: php
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge